/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ical/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ical Feed
         * @description Generate iCal feed for user based on their ical_token.
         */
        get: operations["ical_feed_ical__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Config
         * @description Public config (no auth required).
         */
        get: operations["api_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Me
         * @description Get current user info + ical token.
         */
        get: operations["api_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Watchlist
         * @description Get user's watchlist.
         */
        get: operations["api_watchlist_api_watchlist_get"];
        put?: never;
        /**
         * Api Add Watchlist
         * @description Add a stock to watchlist.
         */
        post: operations["api_add_watchlist_api_watchlist_post"];
        /**
         * Api Remove Watchlist
         * @description Remove a stock from watchlist.
         */
        delete: operations["api_remove_watchlist_api_watchlist_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Earnings
         * @description Get earnings calendar data with layer cache (Issue #7).
         */
        get: operations["api_earnings_api_earnings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/earnings/{earning_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Earning Decision
         * @description Decision-support facts with source-specific unavailable states, never synthetic values.
         */
        get: operations["api_earning_decision_api_earnings__earning_id__decision_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Popular
         * @description Get the list of popular stocks shown by default. Cached (Issue #7).
         */
        get: operations["api_popular_api_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Search Stocks
         * @description Search for stocks to add to watchlist.
         */
        get: operations["api_search_stocks_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Export
         * @description Export earnings data as CSV or JSON.
         */
        get: operations["api_export_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Managed Watchlist */
        get: operations["list_managed_watchlist_api_admin_watchlist_get"];
        put?: never;
        /** Add Managed Watchlist */
        post: operations["add_managed_watchlist_api_admin_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/watchlist/{watchlist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Managed Watchlist */
        put: operations["update_managed_watchlist_api_admin_watchlist__watchlist_id__put"];
        post?: never;
        /** Delete Managed Watchlist */
        delete: operations["delete_managed_watchlist_api_admin_watchlist__watchlist_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sync-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sync Runs */
        get: operations["list_sync_runs_api_admin_sync_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sync-runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Sync Run */
        post: operations["cancel_sync_run_api_admin_sync_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sync-runs/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Stale Runs */
        post: operations["recover_stale_runs_api_admin_sync_runs_recover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Log */
        get: operations["list_audit_log_api_admin_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diagnostics
         * @description Provider metrics and cache diagnostics (Issue #15).
         */
        get: operations["diagnostics_api_admin_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Full dependency health status (Issue #11, #14, #20). No auth required.
         */
        get: operations["health_check_api_admin_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Readiness probe (Issue #14). Returns 200 only when core deps are OK.
         *
         *     Core: PostgreSQL must be healthy. External providers are optional.
         */
        get: operations["readiness_check_api_admin_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sync-runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Sync Run
         * @description Create a retry run from a failed/interrupted/cancelled run (Issue #19).
         */
        post: operations["retry_sync_run_api_admin_sync_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Index */
        get: operations["serve_index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppConfig */
        AppConfig: {
            /**
             * Auth Login Url
             * @default
             */
            auth_login_url: string;
        };
        /** AuditLogEntry */
        AuditLogEntry: {
            /** Id */
            id: number;
            /** Action */
            action: string;
            /** Actor Id */
            actor_id?: string | null;
            /** Actor Email */
            actor_email?: string | null;
            /** Target */
            target?: string | null;
            /**
             * Details
             * @default {}
             */
            details: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at?: string | null;
        };
        /** CacheStats */
        CacheStats: {
            /**
             * Hits
             * @default 0
             */
            hits: number;
            /**
             * Misses
             * @default 0
             */
            misses: number;
            /**
             * Hit Rate
             * @default 0
             */
            hit_rate: number;
            /**
             * Stale Returns
             * @default 0
             */
            stale_returns: number;
            /**
             * Refresh Ok
             * @default 0
             */
            refresh_ok: number;
            /**
             * Refresh Fail
             * @default 0
             */
            refresh_fail: number;
        };
        /** DecisionResponse */
        DecisionResponse: {
            /** Status */
            status: string;
            /** Revision Trend */
            revision_trend?: {
                [key: string]: unknown;
            } | null;
            /** Institution Rating */
            institution_rating?: components["schemas"]["InstitutionRating"] | {
                [key: string]: unknown;
            } | null;
            /** Guidance */
            guidance?: components["schemas"]["GuidanceStatus"] | {
                [key: string]: unknown;
            } | null;
            /** Provenance */
            provenance?: components["schemas"]["Provenance"] | {
                [key: string]: unknown;
            } | null;
        } & {
            [key: string]: unknown;
        };
        /** DiagnosticsResponse */
        DiagnosticsResponse: {
            /**
             * Providers
             * @default {}
             */
            providers: {
                [key: string]: components["schemas"]["ProviderStats"] | {
                    [key: string]: unknown;
                };
            };
            /**
             * @default {
             *       "hits": 0,
             *       "misses": 0,
             *       "hit_rate": 0,
             *       "stale_returns": 0,
             *       "refresh_ok": 0,
             *       "refresh_fail": 0
             *     }
             */
            cache: components["schemas"]["CacheStats"];
            /**
             * Sync Runs 24H
             * @default []
             */
            sync_runs_24h: (components["schemas"]["SyncRunSummary"] | {
                [key: string]: unknown;
            })[];
            /**
             * Recent Syncs
             * @default []
             */
            recent_syncs: (components["schemas"]["RecentSync"] | {
                [key: string]: unknown;
            })[];
        };
        /** EarningItem */
        EarningItem: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
            /**
             * Company Name
             * @default
             */
            company_name: string;
            /**
             * Report Date
             * Format: date
             */
            report_date: string;
            /**
             * Report Type
             * @default Q
             */
            report_type: string;
            /** Fiscal Year */
            fiscal_year?: number | null;
            /** Fiscal Quarter */
            fiscal_quarter?: number | null;
            /** Before After */
            before_after?: string | null;
            /** Eps Estimate */
            eps_estimate?: number | null;
            /** Eps Actual */
            eps_actual?: number | null;
            /** Revenue Estimate */
            revenue_estimate?: number | null;
            /** Revenue Actual */
            revenue_actual?: number | null;
            /**
             * Is Predicted
             * @default false
             */
            is_predicted: boolean;
            /** Date Source */
            date_source?: string | null;
            /** Date Status */
            date_status?: string | null;
            /** Estimate Source */
            estimate_source?: string | null;
            /** Actual Source */
            actual_source?: string | null;
            /** Consensus Eps Gaap */
            consensus_eps_gaap?: number | null;
            /** Consensus Eps Adjusted */
            consensus_eps_adjusted?: number | null;
            /** Consensus Revenue */
            consensus_revenue?: number | null;
            /** Consensus Ebit */
            consensus_ebit?: number | null;
            /** Consensus Net Income */
            consensus_net_income?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** GuidanceStatus */
        GuidanceStatus: {
            /** Status */
            status: string;
            /** Reason */
            reason?: string | null;
            /**
             * Source
             * @default
             */
            source: string;
            /** Checked At */
            checked_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /**
             * Version
             * @default dev
             */
            version: string;
            /**
             * Checks
             * @default {}
             */
            checks: {
                [key: string]: components["schemas"]["SourceCheck"] | {
                    [key: string]: unknown;
                };
            };
        };
        /** InstitutionRating */
        InstitutionRating: {
            /** Currency Symbol */
            currency_symbol?: string | null;
            /** Target Price */
            target_price?: number | null;
            /** Strong Buy */
            strong_buy?: number | null;
            /** Buy */
            buy?: number | null;
            /** Hold */
            hold?: number | null;
            /** Underperform */
            underperform?: number | null;
            /** Sell */
            sell?: number | null;
            /** Recommendation */
            recommendation?: string | null;
            /** Provider Updated At */
            provider_updated_at?: string | null;
            /** Fetched At */
            fetched_at?: string | null;
            /**
             * Source
             * @default
             */
            source: string;
            /** Status */
            status?: string | null;
        };
        /** ManagedWatchlistInput */
        ManagedWatchlistInput: {
            /** Symbol */
            symbol: string;
            /**
             * Market
             * @default US
             */
            market: string;
        };
        /** ManagedWatchlistItem */
        ManagedWatchlistItem: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** OverviewResponse */
        OverviewResponse: {
            /**
             * Source
             * @default {}
             */
            source: components["schemas"]["OverviewSource"] | {
                [key: string]: unknown;
            };
            /**
             * Managed Watchlist
             * @default []
             */
            managed_watchlist: components["schemas"]["ManagedWatchlistItem"][];
        };
        /** OverviewSource */
        OverviewSource: {
            /**
             * Managed Watchlist Count
             * @default 0
             */
            managed_watchlist_count: number;
            /**
             * Last Sync
             * @default {}
             */
            last_sync: {
                [key: string]: unknown;
            };
            /**
             * Source Status
             * @default {}
             */
            source_status: {
                [key: string]: unknown;
            };
        };
        /** PopularStocks */
        PopularStocks: {
            /** Us */
            US: string[];
            /** Hk */
            HK: string[];
        };
        /** Provenance */
        Provenance: {
            /**
             * Revision Trend
             * @default
             */
            revision_trend: string;
            /**
             * Institution Rating
             * @default
             */
            institution_rating: string;
            /**
             * Actual Growth
             * @default
             */
            actual_growth: string;
            /**
             * Price Reaction
             * @default
             */
            price_reaction: string;
        };
        /** ProviderErrorStats */
        ProviderErrorStats: {
            /**
             * Timeout
             * @default 0
             */
            timeout: number;
            /**
             * Rate Limited
             * @default 0
             */
            rate_limited: number;
            /**
             * Connection
             * @default 0
             */
            connection: number;
            /**
             * Invalid Response
             * @default 0
             */
            invalid_response: number;
        };
        /** ProviderStats */
        ProviderStats: {
            /**
             * Calls
             * @default 0
             */
            calls: number;
            /**
             * Success
             * @default 0
             */
            success: number;
            /**
             * Success Rate
             * @default 0
             */
            success_rate: number;
            /**
             * Avg Ms
             * @default 0
             */
            avg_ms: number;
            /**
             * @default {
             *       "timeout": 0,
             *       "rate_limited": 0,
             *       "connection": 0,
             *       "invalid_response": 0
             *     }
             */
            errors: components["schemas"]["ProviderErrorStats"];
        };
        /** ReadyResponse */
        ReadyResponse: {
            /** Status */
            status: string;
        };
        /** RecentSync */
        RecentSync: {
            /** Stage */
            stage: string;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** SearchItem */
        SearchItem: {
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
            /**
             * Company Name
             * @default
             */
            company_name: string;
        };
        /** SourceCheck */
        SourceCheck: {
            /** Status */
            status: string;
            /** Error */
            error?: string | null;
        };
        /** SyncRun */
        SyncRun: {
            /** Id */
            id: number;
            /** Stage */
            stage: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /**
             * Symbol Count
             * @default 0
             */
            symbol_count: number;
            /**
             * Record Count
             * @default 0
             */
            record_count: number;
            /** Error Code */
            error_code?: string | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /**
             * Timeout Seconds
             * @default 3600
             */
            timeout_seconds: number;
            /** Phase */
            phase?: string | null;
            /** Current */
            current?: number | null;
            /** Total */
            total?: number | null;
            /** Idempotency Key */
            idempotency_key?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
        };
        /** SyncRunCancelResult */
        SyncRunCancelResult: {
            /** Status */
            status: string;
            /** Run Id */
            run_id: number;
        };
        /** SyncRunRecoverResult */
        SyncRunRecoverResult: {
            /** Recovered */
            recovered: number;
        };
        /** SyncRunRetryResult */
        SyncRunRetryResult: {
            /** Status */
            status: string;
            /** Original Run Id */
            original_run_id: number;
            /** New Run Id */
            new_run_id: number;
        };
        /** SyncRunSummary */
        SyncRunSummary: {
            /** Status */
            status: string;
            /** Cnt */
            cnt: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Portal User Id */
            portal_user_id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Is Admin */
            is_admin: boolean;
            /** Ical Token */
            ical_token: string;
            /** Ical Url */
            ical_url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchlistAddResult */
        WatchlistAddResult: {
            /** Symbol */
            symbol?: string | null;
            /** Market */
            market?: string | null;
            /** Status */
            status?: string | null;
        };
        /** WatchlistItem */
        WatchlistItem: {
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
        };
        /** WatchlistRemoveResult */
        WatchlistRemoveResult: {
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ical_feed_ical__token__get: {
        parameters: {
            query?: {
                lang?: string;
                scope?: string;
                predicted?: number;
                markets?: string;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    api_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    api_watchlist_api_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItem"][];
                };
            };
        };
    };
    api_add_watchlist_api_watchlist_post: {
        parameters: {
            query: {
                symbol: string;
                market?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistAddResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_remove_watchlist_api_watchlist_delete: {
        parameters: {
            query: {
                symbol: string;
                market?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistRemoveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_earnings_api_earnings_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                watchlistOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EarningItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_earning_decision_api_earnings__earning_id__decision_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                earning_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_popular_api_popular_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopularStocks"];
                };
            };
        };
    };
    api_search_stocks_api_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_export_api_export_get: {
        parameters: {
            query: {
                start: string;
                end: string;
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_admin_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    list_managed_watchlist_api_admin_watchlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedWatchlistItem"][];
                };
            };
        };
    };
    add_managed_watchlist_api_admin_watchlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagedWatchlistInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_managed_watchlist_api_admin_watchlist__watchlist_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagedWatchlistInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedWatchlistItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_managed_watchlist_api_admin_watchlist__watchlist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                watchlist_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sync_runs_api_admin_sync_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_sync_run_api_admin_sync_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunCancelResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recover_stale_runs_api_admin_sync_runs_recover_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunRecoverResult"];
                };
            };
        };
    };
    list_audit_log_api_admin_audit_log_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostics_api_admin_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsResponse"];
                };
            };
        };
    };
    health_check_api_admin_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_check_api_admin_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    retry_sync_run_api_admin_sync_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunRetryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
